name: Dev Engagement Bot

on:
  schedule:
    - cron: "0 */1 * * *"  # every 8 hours
  workflow_dispatch:

jobs:
  issue_engagement:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue + Comment
        run: |
          ISSUE_TITLES=("How would you improve dark mode support?" \
                        "Add support for light mode?" \
                        "Would you like a resume PDF export feature?" \
                        "Should we add theme customization?" \
                        "Mobile responsiveness feedback?")
          
          COMMENTS=("Great idea! Would love to hear others’ opinions." \
                    "We're considering this for the next version." \
                    "Let's discuss possible implementation details.")

          TITLE=${ISSUE_TITLES[$RANDOM % ${#ISSUE_TITLES[@]}]}
          COMMENT=${COMMENTS[$RANDOM % ${#COMMENTS[@]}]}

          ISSUE_DATA=$(jq -n --arg title "$TITLE" '{title: $title, body: "Leave your thoughts below 👇"}')

          ISSUE_NUMBER=$(curl -s -X POST https://api.github.com/repos/${{ github.repository }}/issues \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$ISSUE_DATA" | jq .number)

          curl -s -X POST https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg body "$COMMENT" '{body: $body}')"
